const relevantTeams = [
  "Atalanta",
  "Bologna",
  "Cagliari",
  "Como",
  "Empoli",
  "Fiorentina",
  "Genoa",
  "Hellas Verona",
  "Inter",
  "Benfica",
  "Juventus",
  "Lazio",
  "Lecce",
  "Milan",
  "Monza",
  "Napoli",
  "Parma",
  "Roma",
  "Torino",
  "Udinese",
  "Venezia",
  "Arsenal",
  "Aston Villa",
  "Bournemouth",
  "Brentford",
  "Brighton",
  "Chelsea",
  "Crystal Palace",
  "Everton",
  "Fulham",
  "Ipswich Town",
  "Leicester",
  "Liverpool",
  "Manchester City",
  "Manchester United",
  "Newcastle United",
  "Nottingham Forest",
  "Southampton",
  "Tottenham Hotspur",
  "Tottenham",
  "West Ham",
  "Wolverhampton Wanderers",
  "Wolves",
  "Bayern Munich",
  "Dortmund",
  "Leipzig",
  "Leverkusen",
  "Union Berlin",
  "Freiburg",
  "Wolfsburg",
  "Frankfurt",
  "Fenerbahçe",
  "Galatasaray",
  "Mainz",
  "Borussia Mönchengladbach",
  "PSG",
  "Marseille",
  "Monaco",
  "Olympique Lyonnais",
  "Lille",
  "Rennes",
  "Nice",
  "Lens",
  "Montpellier",
  "Reims",
  "Real Madrid",
  "Barcelona",
  "Atletico Madrid",
  "Atlético Madrid",
  "Sevilla",
  "Real Sociedad",
  "Betis",
  "Villarreal",
  "Athletic Bilbao",
  "Celta Vigo",
  "Valencia",
  "Argentina",
  "Norway",
  "Brazil",
  "France",
  "England",
  "Belgium",
  "Croatia",
  "Netherlands",
  "Italy",
  "Portugal",
  "Spain",
  "Porto",
  "Germany",
  "Mexico",
  "United States",
  "Switzerland",
  "Morocco",
  "Uruguay",
  "Denmark",
  "Japan",
  "Serbia",
  "Colombia",
  "Turkiye",
  "Inter Miami",
];

module.exports = relevantTeams;
