const relevantTeams = [
  "Atalanta",
  "Bologna",
  "Cagliari",
  "Como",
  "Empoli",
  "Fiorentina",
  "Genoa",
  "Hellas Verona",
  "Inter",
  "Juventus",
  "Lazio",
  "Lecce",
  "Milan",
  "Monza",
  "Napoli",
  "Parma",
  "Roma",
  "Torino",
  "Udinese",
  "Venezia",
  "Arsenal",
  "Aston Villa",
  "Bournemouth",
  "Brentford",
  "Brighton",
  "Chelsea",
  "Crystal Palace",
  "Everton",
  "Fulham",
  "Ipswich Town",
  "Leicester",
  "Liverpool",
  "Manchester City",
  "Manchester United",
  "Newcastle United",
  "Nottingham Forest",
  "Southampton",
  "Tottenham Hotspur",
  "Tottenham",
  "West Ham",
  "Wolverhampton Wanderers",
  "Wolves",
  "Bayern Munich",
  "Borussia Dortmund",
  "RB Leipzig",
  "Bayer Leverkusen",
  "Union Berlin",
  "Freiburg",
  "Wolfsburg",
  "Frankfurt",
  "Mainz",
  "Borussia Mönchengladbach",
  "PSG",
  "Marseille",
  "Monaco",
  "Olympique Lyonnais",
  "Lille",
  "Rennes",
  "Nice",
  "Lens",
  "Montpellier",
  "Reims",
  "Real Madrid",
  "Barcelona",
  "Atletico Madrid",
  "Sevilla",
  "Real Sociedad",
  "Betis",
  "Villarreal",
  "Athletic Bilbao",
  "Celta Vigo",
  "Valencia",
  "Argentina",
  "Brazil",
  "France",
  "England",
  "Belgium",
  "Croatia",
  "Netherlands",
  "Italy",
  "Portugal",
  "Spain",
  "Germany",
  "Mexico",
  "United States",
  "Switzerland",
  "Morocco",
  "Uruguay",
  "Denmark",
  "Japan",
  "Serbia",
  "Colombia",
];

module.exports = relevantTeams;
